markdown: redcarpet
highlights: pygments
permalink: /:categories/:title/
paginate: 3

navi:
    - title: About
      url: /about/

    - title: Articles
      url: /articles/

    - title: Life
      url: /Life/


# Site settings
title: 漫漫前端路
author: 
    name: Jiao Xiang
    email: sho.jiao@gmail.com
    github: polly343900
    twitter: polly343900
    weibo: polly343900


