markdown: redcarpet
highlights: pygments
paginate: 4

# Site settings
title: Jekyll Test Blog
description: Just for fun
author: 
    name: Jiao Xiang
    email: sho.jiao@gmail.com
    github: polly343900
    twitter: polly343900


